"""PaymentGateway abstraction. BUILD_SPEC Section 5.

    PaymentGateway (interface): initiate_retry(), check_status(), cancel()
      LocalSimulationGateway(PaymentGateway)  -> self-built, zero external deps
      RazorpayTestGateway(PaymentGateway)     -> razorpay-python, free test mode

Both implementations satisfy this one interface, which is what makes the
Section 5 runtime toggle possible: the decision engine, policy gate, audit trail
and templates are identical either way, and only the payment execution call
differs.

Why the protocol types live here and not in app/enums.py
--------------------------------------------------------
``UpstreamStatus`` describes what a gateway reports about the outside world. It
is never persisted to a column — the engine translates it into ``EventStatus``
and ``PaymentAttemptStatus``, which ARE persisted and do live in app/enums.py.
Keeping it here avoids widening the Session 1 vocabulary with a value no table
stores.

Requests and responses are frozen dataclasses of primitives rather than ORM
objects on purpose: a gateway must not be able to mutate a RiskEvent, and
session 5's Razorpay implementation must be constructible in a test that has no
database at all.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any

from app.enums import EventType, GatewayUsed, PaymentAttemptStatus


class UpstreamStatus(str, Enum):
    """State of the underlying object as the gateway reports it.

    Section 9 requires a re-check of upstream state before executing any
    recovery action; this is the vocabulary that re-check returns.

    PENDING    still owed / not yet resolved — acting is legitimate.
    PAID       settled. Includes the "already resolved externally" case: the
               customer paid on their own and the engine must NOT double-act.
    FAILED     the last attempt failed and no retry is scheduled.
    CANCELLED  cancelled upstream — stop, nothing to recover.
    HALTED     Razorpay subscription end state after its auto-retry also failed.
    ACTIVE     subscription healthy again after a successful retry.
    NOT_FOUND  no such object at the gateway (bad or stale source_ref).
    """

    PENDING = "pending"
    PAID = "paid"
    FAILED = "failed"
    CANCELLED = "cancelled"
    HALTED = "halted"
    ACTIVE = "active"
    NOT_FOUND = "not_found"


#: Statuses meaning "there is nothing left for the engine to recover".
#: ``check_status()`` returning any of these before execution is Section 9's
#: stop-immediately condition.
RESOLVED_UPSTREAM: frozenset[UpstreamStatus] = frozenset(
    {UpstreamStatus.PAID, UpstreamStatus.CANCELLED, UpstreamStatus.ACTIVE}
)

# --------------------------------------------------------------------------- #
# Razorpay-style error-code vocabulary
# --------------------------------------------------------------------------- #
#
# Shared by BOTH gateways and by the synthetic data generator, so the codes the
# generator emits are exactly the codes the simulator reasons about and exactly
# the shape session 5 will see back from the real test sandbox.

#: Codes the Section 6 table treats as HARD: no retry, immediate stop.
#: ``issuer_declined`` (payment_degraded) and ``bank_rejected`` (mandate_failed)
#: are the two the spec names. The policy engine (session 3) is the
#: authoritative gate; gateways also refuse, as defence in depth.
HARD_DECLINE_ERROR_CODES: frozenset[str] = frozenset(
    {
        "GATEWAY_ERROR_ISSUER_DECLINED",
        "BAD_REQUEST_MANDATE_BANK_REJECTED",
    }
)


def is_hard_decline(failure_reason: str | None) -> bool:
    """True when a failure code must never be retried (Section 6)."""
    return failure_reason in HARD_DECLINE_ERROR_CODES


class GatewayError(RuntimeError):
    """Transport-level gateway failure — Section 9's named "gateway failure".

    Raised only when the gateway itself could not be reached or returned an
    unusable response. A payment that simply FAILED is a normal result carried
    in a GatewayResponse, not an exception.
    """

    def __init__(self, message: str, *, gateway: GatewayUsed, source_ref: str | None = None) -> None:
        self.gateway = gateway
        self.source_ref = source_ref
        super().__init__(message)


@dataclass(frozen=True)
class RetryRequest:
    """Everything a gateway needs to attempt one recovery execution.

    ``idempotency_key`` is generated by engine/idempotency.py (session 3) and
    passed through so the gateway can honour Section 9's guarantee that the same
    key never executes twice.
    """

    event_id: str
    source_ref: str
    event_type: EventType
    amount: Decimal
    attempt_number: int
    idempotency_key: str
    #: Gateway error code from the previous failure, e.g.
    #: "BAD_REQUEST_CARD_EXPIRED". Drives the simulator's outcome model and, in
    #: session 5, is what Razorpay itself reported.
    failure_reason: str | None = None
    #: "card" | "upi" | "nach" | "netbanking" | "wallet" | "upi_autopay"
    method: str | None = None


@dataclass(frozen=True)
class GatewayResponse:
    """Result of ``initiate_retry()`` — maps 1:1 onto a PaymentAttempt row."""

    status: PaymentAttemptStatus
    provider_ref: str | None = None
    failure_reason: str | None = None
    #: True when the gateway declined to execute at all because the failure is
    #: non-retryable (Section 6: issuer_declined, bank_rejected -> no retry).
    #: The engine's policy gate is the authoritative stop; this is defence in
    #: depth so a bug upstream cannot cause a retry the spec forbids.
    retry_refused: bool = False
    #: Full synthetic or provider payload, kept verbatim for the audit trail.
    raw: dict[str, Any] = field(default_factory=dict)

    @property
    def succeeded(self) -> bool:
        return self.status == PaymentAttemptStatus.SUCCESS


@dataclass(frozen=True)
class GatewayStatusResult:
    """Result of ``check_status()`` and ``cancel()``."""

    status: UpstreamStatus
    provider_ref: str | None = None
    #: When the gateway has scheduled its OWN retry (Razorpay subscriptions do
    #: this), the instant it will run. The engine must wait rather than forcing
    #: an extra retry — Section 6, subscription_failed row.
    next_retry_at: datetime | None = None
    raw: dict[str, Any] = field(default_factory=dict)

    @property
    def is_resolved_externally(self) -> bool:
        """Section 9: already resolved/cancelled/paid -> stop, do not double-act."""
        return self.status in RESOLVED_UPSTREAM


class PaymentGateway(ABC):
    """The interface both gateways implement. Section 5."""

    #: Which gateway this is; written onto RiskEvent.gateway_used and
    #: PaymentAttempt.gateway_used so the audit trail shows what actually ran.
    name: GatewayUsed

    @abstractmethod
    def initiate_retry(self, request: RetryRequest, *, now: datetime | None = None) -> GatewayResponse:
        """Attempt one recovery execution.

        Implementations MUST be safe to call twice with the same
        ``idempotency_key`` — the second call returns the first result rather
        than executing again (Section 9).
        """

    @abstractmethod
    def check_status(
        self, source_ref: str, event_type: EventType, *, now: datetime | None = None
    ) -> GatewayStatusResult:
        """Report current upstream state.

        Called before every execution as Section 9's race-condition re-check,
        and by the subscription workflow to observe the gateway's own retry.
        """

    @abstractmethod
    def cancel(
        self,
        source_ref: str,
        event_type: EventType,
        *,
        reason: str | None = None,
        now: datetime | None = None,
    ) -> GatewayStatusResult:
        """Cancel the underlying object upstream."""
